[programs.localnet]
gem_bank = "CcqXpbmiqCtpv7wZMJcVrmmjAcNo6Wz4zQiMeQrtbvtC"
gem_farm = "8q6iXyzUS4kWdbQsZs9rU4WNSw6wieW4GdE6dDZsrDka"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/johnwinsor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"